### ISSUE TITLE
Crossing river / narrowgauge:

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#22]
Is this a thing we want to have?
Would be a nice way to get some bonus points for the narrowgauge. Should not provide fast passing speeds, am thinking of 10...20kph here. Thus most players would want to avoid this the second they use long trains (speedbonus) or want a somewhat okayish capacity on their tracks.

**Comment by Leartin** [comment]
We had one for cars before, and that made somewhat sense as a drawbridge to be on the same level. I think I want to redraw that. Are there drawbridges for tracks, or any real-life example that would make sense here?

Otherwise, I think we should have non-navigable rivers, since we don't have many boats anyway. Non-navigable rivers allow bridges to go one level over them, while navigable rivers require two. That means building bridges over those rivers would be much less awkward, especially if the river already spawned with slopes to both sides.

**Comment by Flemmbrav** [comment]
There are drawbridges for tracks in at least Denmark, the Netherlands and Germany. These are for standard gauge and have the overhead cables attached to the moving parts of the bridge (we can't do that sadly). In plus there are vertical lift bridges, that do not have that issue, but lack charm in my opinion. 
I'll attach what I have in mind; This needs fences and weigths still, but the dimensions should fit so far
![Bruecke](https://user-images.githubusercontent.com/44527862/74075900-4f189080-4a15-11ea-923a-cfbf78e30052.png)

The reason the road bridge is not in the set anymore is that the public player would use them instead of actual bridges which results in weird looking cities.

I do welcome the idea of non-navigatable rivers.

**Comment by Leartin** [comment]
I tried to see if it's true the public player would not use actual bridges anymore, sadly it seems cities don't build bridges over rivers at all currently, so I'll report a bug instead.

Edit: Intercity roads use crossings. Welp. I should mention that I don't mind them at all at a flat river. Give them a nice graphic, and they'd look just as good as bridges. I don't like them - at all - if there are slopes to the sides of the river. That's where a bridge is absolutely required to make for a flat road.

**Comment by Flemmbrav** [comment]
Done with https://github.com/Flemmbrav/Pak192.Comic/commit/892c5b1e723c593da51e5a8208144bd68fc012a7
