### ISSUE TITLE
Game does not generate industry

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#28]
With the current pakset, with and without addons, the game does not generate industry. 
This bug appears with both, the initial map creation, as well as increasing the industry densitiy. 
The player is still able to build industry buildings manually.

**Comment by Leartin** [comment]
I suspect an error in the current makeobj. I paked locally, and it worked. I then checked my local pakset against the pakset here and found out that all factories are paked slightly differently, and by exchanging them I could confirm that it's indead the issue.

I'll write a bug report in the German forum, since the International is down at this time.

**Comment by Leartin** [comment]
They work with nightly Simutrans. (https://www.simutrans-forum.de/nightly/)
Probably won't be fixed. At best, we could go back to using a pre-compiled makeobj instead of a fresh nightly makeobj.

**Comment by gpcf** [comment]
It works for me on the simutrans that I compiled from git

**Comment by Flemmbrav** [comment]
It's an issue with the current makeobj nightly, maybe this will be fixed in future versions, otherwise we should go back to an old but stable makeobj version.

**Comment by Leartin** [comment]
We have options:
1) Keep going with what we have set up. In that case, we need to add the Simutrans Nightly link to our readme.
2) Roll back to 121.0 and use a premade makeobj. 
2.1) Stick to 121.0 until 121.1 or 122.0 comes out.
2.2) Stick to 121.0 until we want to use rotatable smoke or another new feature.
3) Have both. This would require a script to adapt dats to either makeobj (eg. if rotatable smoke is used, it probably needs to be replaced by old smoke definition to work with old makeobj)


Personally, I think (3) is too much of a hassle, and I don't like that (2.1) potentially holds back awesome things I want to play with, so for me, it's either (1) or (2.2). What tips the scale is whether or not we want to create a stable release in the near future, since that would need to be 121.0-compatible.

**Comment by Flemmbrav** [comment]
I'd go with 1 by now.

We can go with 3 in the future, but that would require me to finally get the scribt done + solving how to handle comments in the dats.

**Comment by Flemmbrav** [comment]
There's a new version of Simutrans out there, we can use what we have from now on.
