### ISSUE TITLE
Rebuilding project takes a very long time

### ISSUE THREAD

**Issue by gpcf** [Flemmbrav/Pak192.Comic#4]
The pakset compile script should only compile the stuff that has changed, otherwise it takes extremely long to build. I propose having the compile script generate a makefile that finds out which .pak files depend on which files to allow incremental compilation.

**Comment by Leartin** [comment]
The three active team members - Flemmbrav, PTM and myself - are all artists, not coders. We are pretty much happy with a compile script that does everything just by clicking it once, because we compare it to doing all of it manually. I'm sure there are much better ways to handle things, but we simply lack both motivation and ability.
Contributions are always welcome though :)

**Comment by Flemmbrav** [comment]
I wanted to parallelize the building process with qt for windows, but i have no clue when that will happen if it does. I have to do some qt stuff for uni tho, so i guess it will happen in the next few months.
