### ISSUE TITLE
"This combination cannot start!" for BR_475_1-BVG train set

### ISSUE THREAD

**Issue by banacorn** [Flemmbrav/Pak192.Comic#77]
I bought the BR_475_1-BVG train set (hauling a BR_875_1-BVG) and have a schedule set. 
When I press the start button, I get the `This combination cannot start!` message.

It seems like the locomotive is placed behind the passenger wagon.
I'm not sure if this is related #53

**Comment by banacorn** [comment]
Thank you for this lovely pak by the way ❤️!

**Comment by Flemmbrav** [comment]
Heyo banacorn!
You need to add another BR 875 and BR 475 as rear.
They're placed left the ones you bought already.
The Berlin S-Bahn needs at least 4 cars to operate, with the closing two and opening two (you bought the latter) being part of the train.
Hope this helps, otherwise I'll try to add a screenshot.

**Comment by banacorn** [comment]
Thank you for the clarification!
